### ISSUE TITLE
Prepare background masks的代码失效

### ISSUE THREAD

**Issue by YuGong123** [yiranran/APDrawingGAN2#12]
你好，我正在根据你的APDrawingGAN2代码来做 人脸素描合成，但是你的[preprocessing steps](https://github.com/yiranran/APDrawingGAN2/blob/master/preprocess/readme.md) 里的Prepare background masks的代码失效了，你能补充一下吗？

**Comment by yiranran** [comment]
您好，Prepare background masks里用到的"Automatic Portrait Segmentation for Image Stylization"不是我的工作。如果失效了，您可以使用其他的背景提取方法，例如这个issue里提到的方法，谢谢！https://github.com/yiranran/APDrawingGAN/issues/6
