### ISSUE TITLE
Did you guys forget about beards? (curious)

### ISSUE THREAD

**Issue by HarrisDePerceptron** [yiranran/APDrawingGAN2#3]

**Comment by yiranran** [comment]
Do you mean testing on faces with beards?
Here are some results:
<img width="798" alt="rst" src="https://user-images.githubusercontent.com/16771200/84895389-d1584600-b0d4-11ea-99f4-c6bce3dbedcf.png">

**Comment by yiranran** [comment]
We currently do not consider beards as a local region
